# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Início
    url: /
    weight: 10
  - name: Recursos
    url: recursos/
    weight: 20
  - name: Contribua
    url: contribua/
    weight: 30
