# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Início
    url: /
    weight: 10
  - name: Recursos
    url: docs/
    weight: 20
  - name: Contribua
    url: contribua/
    weight: 30

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: contribua
    name: "Contribua"
    pageRef: "/contribua"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3